# Generated by Django 4.0.6 on 2022-07-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_habittracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='name',
            new_name='habit_name',
        ),
        migrations.RemoveField(
            model_name='habittracker',
            name='tracking_goal',
        ),
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='goal_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habittracker',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='habittracker',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_habit_date'),
        ),
    ]
