# Generated by Django 4.0.6 on 2022-07-17 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_created_at_alter_habittracker_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habittracker',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
