# Generated by Django 4.0.6 on 2022-07-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_rename_name_habit_habit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habittracker',
            name='date',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
