# Generated by Django 4.0.6 on 2022-07-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_remove_habittracker_date_user_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habittracker',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
