# Generated by Django 4.0.6 on 2022-07-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habittracker_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habittracker',
            name='unique_habit_date',
        ),
        migrations.AddConstraint(
            model_name='habittracker',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_habittracker'),
        ),
    ]
